[webserver]
web ansible_host=18.215.185.237
[dbserver]
db ansible_host=10.0.2.15 ansible_ssh_common_args='-i /home/apoorva/.ssh/mern-key.pem -o StrictHostKeyChecking=no -o ProxyCommand="ssh -i /home/apoorva/.ssh/mern-key.pem -W %h:%p ubuntu@18.215.185.237"'
[webserver:vars]
ansible_python_interpreter=/usr/bin/python3
[dbserver:vars]
ansible_python_interpreter=/usr/bin/python3
